# This is a basic workflow to help you get started with Actions

name: GITHUB_PAGES

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACTION_TOKEN }}
        TARGET_REPO: XIM-GSAPP/XIM-GSAPP-Fa20
        TARGET_BRANCH: github_pages
        BUILD_SCRIPT: npm install && npm build
        BUILD_DIR: ./docs
